# Basic config
baseURL = "https://pointedsec.github.io/"
theme = "hugo-simple"
languageCode = "es"
title = "Bajo el Teclado"
copyright = "© 2024 pointedsec"
googleAnalytics = "G-ZHDKLM7DD2" # Change layout/partials/google_anaylytics.html

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# https://github.com/gohugoio/hugo/issues/12152
capitalizeListTitles = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
# ignoreErrors = ["error-disable-taxonomy"]
[taxonomies]
tag = "tags"

[markup]
  defaultMarkdownHandler = 'goldmark'
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 1
endLevel = 4
[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "catppuccin-frappé"

[params]
title = "Bajo el Teclado"
description = "Blog personal de pointedsec"
favicon = "pointed.png"
dateFormat = "2006-01-02"
hideMadeWithLine = true
hideRSSLink = true

[params.author]
name = "Andrés Del Cerro"
email = "adelcerrorodriguez@gmail.com"

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10
[[menu.main]]
name = "Writeup's"
pageRef = "/writeups"
weight = 20
[[menu.main]]
name = "About me"
pageRef = "/about"
weight = 20

[pagination]
pagerSize = 16